services:
  wordpress:
    build:
      context: ./wordpress_data
    image: wordpress:latest
    user: root
    container_name: azntaiji-com-wordpress
    restart: always
    external_links:
      - mysql-db
    volumes:
      - ./wordpress_data:/var/www/html:rw
    networks:
      - reverse-proxynet
    environment:
      - WORDPRESS_DB_HOST=mysql-db
      - WORDPRESS_DB_PORT_NUMBER=3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=${DB_ROOT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxynet"
      - "traefik.http.routers.azntaiji-website.rule=Host(`azntaiji.com`) || Host(`www.azntaiji.com`)"
      - "traefik.http.routers.azntaiji-website.entrypoints=web,websecure"
      - "traefik.http.routers.azntaiji-website.tls.certresolver=myresolver"
      #- "traefik.http.services.azntaiji-website.loadbalancer.server.port=8085"
      - "traefik.http.routers.azntaiji-website.middlewares=https_redirect@docker,non_www@docker"
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true