services:
  wordpress:
    build:
     context: ./wordpress_data
    image: wordpress:latest
    user: root
    container_name: azntaiji-com-wordpress
    restart: always
    volumes:
      - ./wordpress_data:/var/www/html:rw
    networks:
      - reverse-proxynet
      - phpmyadmin
    env_file:
      - env/wordpress.env
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxynet"
      - "traefik.http.routers.azntaiji-website.rule=Host(`azntaiji.com`) || Host(`www.azntaiji.com`)"
      - "traefik.http.routers.azntaiji-website.entrypoints=web,websecure"
      - "traefik.http.routers.azntaiji-website.tls.certresolver=myresolver"
      #- "traefik.http.services.azntaiji-website.loadbalancer.server.port=8085"
      - "traefik.http.routers.azntaiji-website.middlewares=https_redirect@docker,non_www@docker"
  redis:
    image: redis:6
    restart: always
    ports:
     - 6379:6379
    networks:
     - phpmyadmin
    entrypoint: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true
  phpmyadmin:
    name: phpmyadmin
    external: true